import {
  cuartoMisterioDoloroso,
  cuartoMisterioDolorosoDescripcion,
  primerMisterioDoloroso,
  primerMisterioDolorosoDescripcion,
  segundoMisterioDoloroso,
  segundoMisterioDolorosoDescripcion,
  tercerMisterioDoloroso,
  tercerMisterioDolorosoDescripcion,
  quintoMisterioDoloroso,
  quintoMisterioDolorosoDescripcion,
} from "./dolorosos";

import {
  cuartoMisterioGlorioso,
  cuartoMisterioGloriosoDescripcion,
  primerMisterioGlorioso,
  primerMisterioGloriosoDescripcion,
  segundoMisterioGlorioso,
  segundoMisterioGloriosoDescripcion,
  tercerMisterioGlorioso,
  tercerMisterioGloriosoDescripcion,
  quintoMisterioGlorioso,
  quintoMisterioGloriosoDescripcion,
} from "./gloriosos";

import {
  cuartoMisterioGozoso,
  cuartoMisterioGozosoDescripcion,
  primerMisterioGozoso,
  primerMisterioGozosoDescripcion,
  segundoMisterioGozoso,
  segundoMisterioGozosoDescripcion,
  tercerMisterioGozoso,
  tercerMisterioGozosoDescripcion,
  quintoMisterioGozoso,
  quintoMisterioGozosoDescripcion,
} from "./gozosos";

import {
  cuartoMisterioLuminoso,
  cuartoMisterioLuminosoDescripcion,
  primerMisterioLuminoso,
  primerMisterioLuminosoDescripcion,
  segundoMisterioLuminoso,
  segundoMisterioLuminosoDescripcion,
  tercerMisterioLuminoso,
  tercerMisterioLuminosoDescripcion,
  quintoMisterioLuminoso,
  quintoMisterioLuminosoDescripcion,
} from "./luminosos";

export {
  cuartoMisterioDoloroso,
  cuartoMisterioDolorosoDescripcion,
  primerMisterioDoloroso,
  primerMisterioDolorosoDescripcion,
  segundoMisterioDoloroso,
  segundoMisterioDolorosoDescripcion,
  tercerMisterioDoloroso,
  tercerMisterioDolorosoDescripcion,
  quintoMisterioDoloroso,
  quintoMisterioDolorosoDescripcion,
  cuartoMisterioGlorioso,
  cuartoMisterioGloriosoDescripcion,
  primerMisterioGlorioso,
  primerMisterioGloriosoDescripcion,
  segundoMisterioGlorioso,
  segundoMisterioGloriosoDescripcion,
  tercerMisterioGlorioso,
  tercerMisterioGloriosoDescripcion,
  quintoMisterioGlorioso,
  quintoMisterioGloriosoDescripcion,
  cuartoMisterioGozoso,
  cuartoMisterioGozosoDescripcion,
  primerMisterioGozoso,
  primerMisterioGozosoDescripcion,
  segundoMisterioGozoso,
  segundoMisterioGozosoDescripcion,
  tercerMisterioGozoso,
  tercerMisterioGozosoDescripcion,
  quintoMisterioGozoso,
  quintoMisterioGozosoDescripcion,
  cuartoMisterioLuminoso,
  cuartoMisterioLuminosoDescripcion,
  primerMisterioLuminoso,
  primerMisterioLuminosoDescripcion,
  segundoMisterioLuminoso,
  segundoMisterioLuminosoDescripcion,
  tercerMisterioLuminoso,
  tercerMisterioLuminosoDescripcion,
  quintoMisterioLuminoso,
  quintoMisterioLuminosoDescripcion,
};
